### PR TITLE
Task2

### PR DESCRIPTION
**Pull request by kirban**

### CODE REVIEW

**Review by MikeShakmakov — APPROVED** [review]
Everything is needed for 5 score is done with minimum effort ).
The npm script for automated build is checked manually.

**Comment by ReshetovItsMe** [comment]
@Mike--S, have you submit score for the task? I also have been assigned to this PR, but I can't see that cross-check already submitted.
@kirban, do you have some score?

**Comment by ReshetovItsMe** [comment]
From my side reviewed

**Comment by MikeShakmakov** [comment]
> @Mike--S, have you submit score for the task? I also have been assigned to this PR, but I can't see that cross-check already submitted.

I submitted the score yesterday, yeap. I thought that the final score is avarage of several scores from different people... And I think it will be updated again somehow manually as usual.

**Pull request merged**
